'use client';
import {useState} from 'react';
const chapters = [
 {name:'Jakarta',group:'JABODETABEK',code:'JKT'}, {name:'Bogor',group:'JABODETABEK',code:'BGR'}, {name:'Depok',group:'JABODETABEK',code:'DPK'}, {name:'Tangerang',group:'JABODETABEK',code:'TGR'}, {name:'Bekasi',group:'JABODETABEK',code:'BKS'},
 {name:'Cikarang',group:'CIKAPUR',code:'CKR'}, {name:'Karawang',group:'CIKAPUR',code:'KRW'}, {name:'Purwakarta',group:'CIKAPUR',code:'PWK'}, {name:'Semarang',group:'MANDIRI',code:'SMG'}, {name:'Deli Serdang',group:'MANDIRI',code:'DLS'}, {name:'Malang Raya',group:'MANDIRI',code:'MLG'}
];
const national=[{role:'FOUNDER',description:'Pendiri komunitas',number:'01'},{role:'KETUA UMUM NASIONAL',description:'Pimpinan nasional CSI',number:'02'},{role:'WAKIL KETUA UMUM NASIONAL',description:'Wakil pimpinan nasional',number:'03'},{role:'BENDAHARA',description:'Pengelolaan keuangan',number:'04'},{role:'DIVISI IT',description:'Teknologi dan platform digital',number:'05'},{role:'DIVISI KEANGGOTAAN',description:'Pengelolaan anggota dan onboarding CSI',number:'06'}];
const events=[{n:'01',title:'Touring & Riding',desc:'Jelajahi jalanan, bangun cerita dan persaudaraan.'},{n:'02',title:'Kopdar & Gathering',desc:'Ruang silaturahmi antarchapter dan anggota.'},{n:'03',title:'Aksi Sosial',desc:'Solidaritas yang terasa hingga ke masyarakat.'}];
export default function Home(){
 const [tab,setTab]=useState<'nasional'|'wilayah'|'mandiri'>('nasional');
 const [filter,setFilter]=useState('SEMUA');
 const [menu,setMenu]=useState(false);
 const filtered=chapters.filter(c=>filter==='SEMUA'||c.group===filter);
 return <>
 <header className="header"><a href="#home" className="brand"><span className="brandMark">CSI<span className="brandSlash">/</span></span><span className="brandText">CBR SQUAD<br/><small>INDONESIA</small></span></a><button type="button" className="hamburger" aria-label="Buka navigasi" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?'nav open':'nav'}><a href="#tentang" onClick={()=>setMenu(false)}>TENTANG</a><a href="#regional" onClick={()=>setMenu(false)}>REGIONAL</a><a href="#organisasi" onClick={()=>setMenu(false)}>ORGANISASI</a><a href="#kegiatan" onClick={()=>setMenu(false)}>KEGIATAN</a><a className="navJoin" href="/under-construction" onClick={()=>setMenu(false)}>GABUNG CSI ↗</a></nav></header>
 <main><section id="home" className="hero"><div className="heroShade"/><div className="heroInner"><div className="eyebrow"><span className="redline"/> INDONESIAN CBR COMMUNITY <span className="heroDot">●</span> EST. —</div><h1>KEEP<br/>SOLID AND <span>SAFETY RIDE.</span></h1><p>Satu passion. Banyak wilayah. Satu keluarga. Selamat datang di CBR Squad Indonesia — tempat perjalanan menjadi persaudaraan.</p><div className="heroActions"><a className="btn btnRed" href="#regional">JELAJAHI REGIONAL <span>↗</span></a><a className="btn btnGhost" href="#tentang">KENALI CSI ↓</a></div></div><div className="heroFoot"><span>ONE PASSION <b>✦</b> ONE BROTHERHOOD <b>✦</b> ONE SQUAD</span><span>SCROLL TO EXPLORE ↓</span></div></section>
 <section className="ticker" aria-label="Identitas komunitas"><div>RIDE TOGETHER <b>✦</b> STAY UNITED <b>✦</b> CBR SQUAD INDONESIA <b>✦</b> RIDE TOGETHER <b>✦</b> STAY UNITED</div></section>
 <section id="tentang" className="section about"><div><p className="kicker">01 / WHO WE ARE</p><h2>LEBIH DARI<br/><span>KOMUNITAS.</span></h2></div><div className="aboutRight"><p className="lead">CSI adalah wadah persaudaraan para pecinta Honda CBR yang terhubung lintas kota dan lintas pulau.</p><p>Berawal dari kecintaan yang sama terhadap roda dua, kami membangun ruang untuk berbagi, bertumbuh, berkendara dengan aman, dan memberikan dampak positif melalui kegiatan komunitas.</p><div className="pillrow"><span>SOLIDARITAS</span><span>SAFETY RIDING</span><span>KEBERSAMAAN</span></div></div></section>
 <section id="regional" className="section regional"><div className="sectionTop"><div><p className="kicker">02 / OUR TERRITORY</p><h2>SATU SQUAD.<br/><span>BANYAK KOTA.</span></h2></div><p>Temukan keluarga CSI di berbagai wilayah Indonesia.</p></div><div className="filters">{['SEMUA','JABODETABEK','CIKAPUR','MANDIRI'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='MANDIRI'?'REGIONAL MANDIRI':f}</button>)}</div><div className="chapterGrid">{filtered.map((c,i)=><article className="chapter" key={c.code}><div className="chapterHead"><span>{String(i+1).padStart(2,'0')} / {c.group}</span><span>↗</span></div><div className="chapterCode">{c.code}</div><div className="chapterBottom"><h3>{c.name}</h3><p>{c.group==='MANDIRI'?'REGIONAL MANDIRI':`KORWIL ${c.group}`}</p></div></article>)}</div><p className="note">Wilayah yang ditampilkan mengikuti struktur komunitas yang diberikan. Nama dan kontak pengurus dapat ditambahkan nanti.</p></section>
 <section id="organisasi" className="section organization"><div className="sectionTop"><div><p className="kicker">03 / THE PEOPLE</p><h2>STRUKTUR<br/><span>ORGANISASI.</span></h2></div><p>Dari pengurus nasional hingga para pemimpin di setiap daerah.</p></div><div className="tabs" role="tablist" aria-label="Tingkat organisasi"><button role="tab" aria-selected={tab==='nasional'} className={tab==='nasional'?'active':''} onClick={()=>setTab('nasional')}>01 / NASIONAL</button><button role="tab" aria-selected={tab==='wilayah'} className={tab==='wilayah'?'active':''} onClick={()=>setTab('wilayah')}>02 / KOORDINATOR WILAYAH</button><button role="tab" aria-selected={tab==='mandiri'} className={tab==='mandiri'?'active':''} onClick={()=>setTab('mandiri')}>03 / REGIONAL MANDIRI</button></div>
 {tab==='nasional'&&<div className="orgGrid">{national.map((n)=><article className="orgCard" key={n.role}><span className="orgNumber">{n.number} / NATIONAL</span><div className="avatar">✦</div><h3>{n.role}</h3><p>{n.description}</p><span className="vacant">NAMA PENGURUS MENYUSUL</span></article>)}</div>}
 {tab==='wilayah'&&<div className="wilayahGrid">{[{title:'JABODETABEK',cities:['Jakarta','Bogor','Depok','Tangerang','Bekasi']},{title:'CIKAPUR',cities:['Cikarang','Karawang','Purwakarta']}].map((w)=><article className="wilayah" key={w.title}><div className="wilayahTitle"><div><span>KOORDINATOR WILAYAH</span><h3>{w.title}</h3></div><span className="avatarSmall">✦</span></div><p className="korwilPlaceholder">NAMA KOORDINATOR MENYUSUL</p><div className="cityList">{w.cities.map((c,i)=><div key={c}><span>{String(i+1).padStart(2,'0')}</span><strong>KETUA UMUM {c.toUpperCase()}</strong><small>Nama pengurus menyusul</small></div>)}</div></article>)}</div>}
 {tab==='mandiri'&&<div className="wilayahGrid">{['Semarang','Deli Serdang','Malang Raya'].map((c,i)=><article className="wilayah independent" key={c}><span className="orgNumber">0{i+1} / REGIONAL MANDIRI</span><div className="avatar">✦</div><h3>KETUA UMUM<br/><em>{c.toUpperCase()}</em></h3><p>Regional mandiri CSI</p><span className="vacant">NAMA PENGURUS MENYUSUL</span></article>)}</div>}
 <p className="note">Struktur jabatan berdasarkan informasi CSI. Foto, nama, periode, dan detail kewenangan dapat dilengkapi saat data resmi tersedia.</p></section>
 <section id="kegiatan" className="section activities"><p className="kicker">04 / WHAT WE DO</p><h2>BUKAN CUMA<br/><span>DI JALAN.</span></h2><div className="eventList">{events.map(e=><div className="event" key={e.n}><span>{e.n}</span><h3>{e.title}</h3><p>{e.desc}</p><span className="eventArrow">↗</span></div>)}</div></section>
 <section id="gabung" className="join"><div className="joinNoise"/><div className="joinInner"><p className="kicker">05 / JOIN THE MOVEMENT</p><h2>YOUR RIDE.<br/>OUR <span>SQUAD.</span></h2><p>Ingin menjadi bagian dari CSI? Saat ini form pendaftaran masih dalam tahap pembangunan.</p><a className="btn btnLight" href="/under-construction">GABUNG CSI ↗</a><small>Pendaftaran member akan dibuka segera.</small></div></section></main>
 <footer><div className="footerBrand">CSI<span>/</span><small>CBR SQUAD INDONESIA</small></div><p>ONE PASSION. ONE BROTHERHOOD. ONE SQUAD.</p><a href="#home">BACK TO TOP ↑</a><div className="footerBottom">© {new Date().getFullYear()} CBR SQUAD INDONESIA <span>BUILT FOR THE BROTHERHOOD</span></div></footer>
 </>;
}
